Initial
digitalbazaar/bedrock-multikey-context pull request #1
Opened 2022-09-13 14:47 UTC by aljones15

Awaiting second PR for data integrity context.

2022-09-19 16:16 UTC, gannan08 commented on LICENSE.md
> +Copyright (c) 2011-2019 Digital Bazaar, Inc.
```suggestion
Copyright (c) 2011-2022 Digital Bazaar, Inc.
```

2022-09-19 16:17 UTC, gannan08 approved these changes

2022-09-19 16:18 UTC, gannan08 commented on package.json
> +    "node": ">=12.0.0"
```suggestion
    "node": ">=16.0.0"
```

2022-09-19 16:29 UTC, dlongley requested changes

2022-09-19 16:29 UTC, dlongley commented on CHANGELOG.md
> +#bedrock-multikey-context CHANGELOG
```suggestion
# bedrock-multikey-context CHANGELOG
```

2022-09-19 16:29 UTC, dlongley commented on README.md
> +#bedrock multikey context
```suggestion
# bedrock multikey context
```

2022-09-19 16:29 UTC, dlongley commented on package.json
> +    "bedrock-jsonld-document-loader": "^1.0.0"
Needs to be fixed.

2022-09-20 13:09 UTC, aljones15 commented on package.json
> +    "@bedrock/core": "^6.0.0",
@dlongley @gannan08 should I drop this peer dep of `@bedrock/core` or should I keep it?

2022-09-20 15:02 UTC, aljones15 commented on package.json
> +    "@bedrock/core": "^6.0.0",
Removed `@bedrock/core` peerDep here: https://github.com/digitalbazaar/bedrock-multikey-context/pull/1/commits/885fc2561defe9267b9586df7fb989080b8acd6a

2022-09-20 15:03 UTC, aljones15 commented on package.json
> +    "bedrock-jsonld-document-loader": "^1.0.0"
Addressed the namespace issue here: https://github.com/digitalbazaar/bedrock-multikey-context/pull/1/commits/82b6db4b6524bcd9de00a27b87429afeeed3610a

2022-09-20 15:31 UTC, dlongley approved these changes
Approving -- and I'll fix the package.json issues, just noting them here for you to see.

2022-09-20 15:31 UTC, dlongley commented on package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.0.1",
```

2022-09-20 15:31 UTC, dlongley commented on package.json
> +    "url": "git+https://github.com/digitalbazaar/bedrock-multikey-context.git"
```suggestion
    "url": "https://github.com/digitalbazaar/bedrock-multikey-context.git"
```

2022-09-20 15:31 UTC, merged